version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
    # depends_on: # à décommenter quand le backend sera prêt.
    #   - backend # à décommenter quand le backend sera prêt.

  bdd:
    image: mariadb:11.7.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: wonderbook
    ports:
      - "3306:3306"
    volumes:
      - "C:/wonderbdd:/var/lib/mysql"  # Volume persistant pour les données MariaDB

## ------------------BACKEND------------ à décommenter quand le code backend sera prêt
  # backend:
  #   build: ./rep_vers_code_API
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpwd
  #     MYSQL_DATABASE: wonderbook
  #   depends_on:
  #     - bdd